/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PostsidImport } from './routes/posts/[id]'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsidRoute = PostsidImport.update({
  id: '/posts/[id]',
  path: '/posts/[id]',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/[id]': {
      id: '/posts/[id]'
      path: '/posts/[id]'
      fullPath: '/posts/[id]'
      preLoaderRoute: typeof PostsidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/[id]': typeof PostsidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/[id]': typeof PostsidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/posts/[id]': typeof PostsidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts/[id]'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts/[id]'
  id: '__root__' | '/' | '/posts/[id]'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsidRoute: typeof PostsidRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsidRoute: PostsidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/posts/[id]"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/posts/[id]": {
      "filePath": "posts/[id].tsx"
    }
  }
}
ROUTE_MANIFEST_END */
